name: Deploy WebGL client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            rm -rf /opt/rspserver/app/static/game-client/*
            mkdir -p /opt/rspserver/app/static/game-client

      - name: Upload new build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/opt/rspserver/app/static/game-client/"
          strip_components: 0

      - name: Check remote hash
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets_SSH_USER }}
          key: ${{ secrets_SSH_KEY }}
          script: |
            cd /opt/rspserver/app/static/game-client
            sha256sum index.html
